payment_service_port: "tiger-payment:8001"
inventory_service_port: "tiger-inventory:8000"
service_port: "8080"

inventory_config: 
  inventory_file_path: "./inventory.yml"

#  UNCOMMENT FOR LOCAL W/O DOCKER
# payment_service_port: ":8001"
# inventory_service_port: ":8000"
# service_port: "8080"