version: '3.9'

services:
  bff:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes: 
      - .:/opt/tigercoders/bff
      - ~/.ssh:/root/ssh
    ports: 
      - "8080:8080"
  
    